const constants = {
  ZERO_TO_FIVE: 'ZERO_TO_FIVE',
  FIVE_TO_TWENTY_FIVE: 'FIVE_TO_TWENTY_FIVE',
  TWENTY_FIVE_TO_SEVENTY_FIVE: 'TWENTY_FIVE_TO_SEVENTY_FIVE',
  SEVENTY_FIVE_TO_NINETY_FIVE: 'SEVENTY_FIVE_TO_NINETY_FIVE', 
  NINETY_FIVE_TO_ONE_HUNDRED: 'NINETY_FIVE_TO_ONE_HUNDRED',
};

export default constants;